.TH SAFEDEL 1 "OCT 2019" Linux "User Manuals"
.SH NAME
Monitor \- Command for deleting regular files to a special folder called .trashCan
.SH SYNOPSIS
.B ./safeDel.sh "-m"
.SH DESCRIPTION
.B Monitor
It monitors changes in the trashCan folder
.BR xyzzy (1)
linker to find them. The symdef entry is then compressed
using the WBG (Whiz-Bang-Gizmo) algorithm.
All files are processed in the order specified.
.SH OPTIONS
none
.SH BUGS
Combining it with arguments may generate few bugs
.SH AUTHOR
Ticio Torcato Fortuna Victoriano
.SH "SEE ALSO"
.BR inotify-tool (1),